### PR TITLE
Update Shopify Embedded App

### LINKED ISSUE #39: Latest update breaks app
@EiNSTeiN- 

Your update yesterday broke the app.

```
=> Booting Thin
=> Rails 4.2.5.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/tajima/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/less-rails-2.7.0/lib/less/rails/railtie.rb:19:in `block in <class:Railtie>': undefined method `register_preprocessor' for nil:NilClass (NoMethodError)
```

Reverting to commit aaabbd4350831fb0de903969bf6c67d08764a6d7 works fine:

```
HEAD is now at aaabbd4... Merge pull request #38 from mootpt/patch-1
tajima@MacBook-Pro ~/projects/embedded-app-example[(detached from aaabbd4)*]$ rails s
=> Booting Thin
=> Rails 4.2.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on localhost:3000, CTRL+C to stop
```

### PR DESCRIPTION
**Pull request by julionc**
Hey guys
The main purpose of this PR is Rails 4.2.x support. I updated the Shopify embedded app example.
Supporting details are:
* Ruby: `2.2.4`
* Rails: `4.2.5.1`
* Shopify App: `6.4.2`

Fixes #39

### CODE REVIEW

**Comment by julionc** [comment]
cc @celsodantas @kevinhughes27 @kmcphillips

**Comment by kevinhughes27** [comment]
I appreciate the update - makes me wonder though why do we still have this repo? @celsodantas @kmcphillips I think we should remove this in favour of https://github.com/Shopify/shopify_app. We can add the relevant view example code into an example in that repo. I think this would be easier for us to keep up to date.

@ShayneP @joshubrown @jamiemtdwyer @dtKinger what do you guys think about this?

**Comment by dtKinger** [comment]
@kevinhughes27 From my perspective, I see that this repo is linked to from three docs:

* https://docs.shopify.com/api/libraries/full-listing
* https://docs.shopify.com/shopify-pos-app-sdk/examples
* https://docs.shopify.com/embedded-app-sdk/examples

So if the changes you're proposing still work with the embedded app SDK and the POS app SDK, then I'm happy.

**Comment by celsodantas** [comment]
This app is useful as an example of how to deal with the embedded app JS. It's just an example. So I think it's useful.

The problem is that people use this as a base to build the app and not as a reference. =/
Can we update the docs to let people know that? Or maybe simplify this app to not be a rails app but just a JS app?

I'm not against removing this repo in favor of `shopify_app` but I see some value in the repo. It's easier for people to see code in action than a code generation tool.

**Comment by kevinhughes27** [comment]
I'm proposing we move it to a sub-directory in ShopifyApp

**Comment by celsodantas** [comment]
cc @dominiquesr

**Comment by dominiquesr** [comment]
@dtKinger - where did we end up putting Shayne's sample app compared to Kevin's Sinatra sample? These shouldn't necessarily live together just want to see if there's a consistent approach we can use.

**Comment by dtKinger** [comment]
We put that here:

https://github.com/Shopify/example-ruby-app/

**Comment by dominiquesr** [comment]
I can't check right now since I'm not at my laptop, but if the example
embedded app was generated using Shopify_app then creation an example
folder in there is a great idea. Make sure that each example has its own
subdirectory so that we can add more examples to that directory in the
future.

If not then we can create a repo with all of our examples that we use in
the docs.

We put that here:

https://github.com/Shopify/example-ruby-app/

—
Reply to this email directly or view it on GitHub
<https://github.com/Shopify/embedded-app-example/pull/40#issuecomment-181987854>
.

**Comment by kevinhughes27** [comment]
Okay sounds like everyone is onboard to move this example to ShopifyApp. I'll make the move when I have a sec then I'll coordinate with @dtKinger to have the docs updated

**Comment by kmcphillips** [comment]
:trophy:

**Comment by celsodantas** [comment]
guh3mjd

**Comment by julionc-teclalabs** [comment]
:+1: LGTM

**Comment by julionc** [comment]
:+1: LGTM

**Comment by kevinhughes27** [comment]
I've opened a PR to move this over to Shopify App https://github.com/Shopify/shopify_app/pull/218

**Comment by julionc** [comment]
kudos to @kevinhughes27 and the Shopify Team.

> This example has moved. It's now part of the [Shopify App repo](https://github.com/Shopify/shopify_app).

**Pull request closed without merging**
