### PR TITLE
Bump to Rails 4.2.0

### PR DESCRIPTION
**Pull request by haeky**
Updating Rails to 4.2.0 and Ruby to 2.1.5

ping @kmcphillips @jamesmacaulay 
/cc @celsodantas @davidcornu

### CODE REVIEW

**Comment by kmcphillips** [comment]
Can you add a `bin/setup` script if you're bumping to 4.2?
https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/bin/setup

**Comment by kmcphillips** [comment]
https://github.com/rails/rails/pull/15189

**Comment by kmcphillips** [comment]
Need to set `config.eager_load`

**Comment by kmcphillips** [comment]
You also need to set up your `secrets.yml`. There's deprecation warnings with your secret key.

```
DEPRECATION WARNING: You didn't set `secret_key_base`. Read the upgrade documentation to learn more about this new config option. (called from require at script/rails:6)
```

**Comment by kmcphillips** [comment]
Did you run `rake rails:update`?

Read through this and look for anything you may have missed. http://edgeguides.rubyonrails.org/4_2_release_notes.html

**Comment by haeky** [comment]
I just ran it and added all the new files, this should be safe now. Could you :tophat: it one more time?

**Comment by haeky** [comment]
I've pass though all the DEPRECATED warnings

**Comment by kmcphillips** [comment]
:+1:

**Comment by celsodantas** [comment]
:+1: to me

**Pull request merged**
